### PR TITLE
add multiple restaurants(branches) support for single client

### PR DESCRIPTION
**Pull request by alexandrter**
https://trello.com/c/7klEL329/109-refactor-db-stucture

### CODE REVIEW

**Comment by alexandrter** [comment]
Originally I did not like t_restaurant name because it's now a branch and t_restaurant does not really speak for itself wether it's just a branch or a whole franchise. Now I hate it. What do you think? Should I change it to t_branch? There will be more changes on backend than, but we are currently rewriting it almost completely anyway.

P.S. Do not merge until backend PR is ready

**Comment by donesvad** [comment]
@alexandrter could add a screenshot of the refactored DB diagram, please?

**Comment by donesvad** [comment]
> @alexandrter could add a screenshot of the refactored DB diagram, please?

image_2023-04-13_09-51-41

**Comment by alexandrter** [comment]
updated diagram
image

**Review by donesvad — APPROVED** [review]
lgtm

**Comment by alexandrter** [comment]
duplicate of https://github.com/murano-app/murano-db/pull/28

**Pull request closed without merging**
